repos:
  - repo: local
    hooks:
      - id: isort
        name: Re-order Python imports
        language: python
        entry: isort
        types: [python]

      - id: black
        name: Re-format Python files
        language: python
        entry: black
        types: [python]

      - id: flake8
        name: Lint Python files
        language: python
        entry: flake8
        types: [python]
        require_serial: true